### ISSUE TITLE
TSOM CCP実装

### ISSUE THREAD

**Issue by TetraMiyazaki** [furukawa-laboratory/ExploreSearchSystem#1]

**Comment by TetraMiyazaki** [comment]
https://github.com/furukawa-laboratory/demo-visual-analytics-set-data/blob/4c1c6575760c64adb79e1e71f719496f9b48dd90/gmm_net/models/base_gmm_net.py#L149
渡辺さんコード

**Comment by TetraMiyazaki** [comment]
https://dash.plotly.com/interactive-graphing

**Comment by tanacchi** [comment]
dash.py 249 行目の history の key に何があるのか見たいですね

**Comment by TetraMiyazaki** [comment]
いけた・・・・しょうもなさすぎた
![image](https://user-images.githubusercontent.com/12492226/138132395-15fa4b0f-5a0b-43ee-be75-b48087433890.png)
